### ISSUE TITLE
AimsRegisterBMEstimate does not estimate correct registration anymore

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/aims-free#55]
This issue is only on master branch. The AimsRegisterBMEstimate of 5.0 branch is OK.
Here are the command to test registration:
```
'AimsRegisterBMEstimate' '-r' 'reference.nii' '-t' 'test.nii' '--iter' '5' '--start' '3' '--stop' '1' '-n' 'transfo.trm' '--transfo' '1' '-ct' '4' '-cr' '4' -o 'registered.nii'
```
and the dataset to reproduce the issue: [data.zip](https://github.com/brainvisa/aims-free/files/6433737/data.zip)

AimsRegisterBMEstimate of **master** branch estimates the transformation:
```
[[ -17.7782, -12.8181,   -10.8379,  52.5388 ],
 [  22.8468,  15.3103,    15.1563, -57.1393 ],
 [        0,        0,          1,        0 ]]
```
whereas AimsRegisterBMEstimate of **5.0** branch estimates the transformation:
```
[[ 0.993479, 0.114028,          0, -0.528057 ],
 [ -0.114028, 0.993479,          0, 0.778622 ],
 [        0,        0,          1,        0 ]]
```

I think this is related to recent changes on volumes, but I have to check this hypothesis

**Comment by denisri** [comment]
Well, that doesn't seem easy because I don't know what this command does, nor how it works.
Maybe we will have to do a dichotomy in the history of aims-free, and/or compare step by step what 5.0 and master versions do by printing lots of things in both versions.

**Comment by nsouedet** [comment]
I am currently comparing with version 5.0, it seems it comes from the deepcopy use in least_square_estimation_d.h, but I am currently verifying it :)

**Comment by nsouedet** [comment]
It is not the new deepcopy use ...

**Comment by denisri** [comment]
13123c45075a473c7f2fc695f551529b6f2e91dd on 2021/04/27 was also OK. Note that I don't have exactly the same results as you:
```
Motion estimated is: 
[[ 0.993265, 0.115884,          0, -0.533378 ],
 [ -0.115884, 0.993265,          0, 0.808544 ],
 [        0,        0,          1,        0 ]]
```
but it's far closer than the current main branch ;)

**Comment by nsouedet** [comment]
It is related the method transform of DecomposedMotion does not seems to return same result as before

**Comment by denisri** [comment]
That's plausible yes, I have replaced AimsData with VolumeRef in transformation classes. The behaviour should be the same but I may have done a mistake...

**Comment by denisri** [comment]
In e995ff24f0e73007be784fb78a7e0a7f546b462c (2021/05/03) it was broken.

**Comment by nsouedet** [comment]
Fine, we know where it comes from :), that is always a good news !

**Comment by nsouedet** [comment]
The guilty could be 7fb54f34359bedd7a7ba12d8be183283227d61cd (28/04/2021)

**Comment by denisri** [comment]
I think I have found the problem, this was in re-coding the matrix product for Volume (volumeutil_d.h):
AimsData:
```
  for ( long y = 0; y < other.dimY(); y++ )
    for ( long x = 0; x < dimX(); x++ )
    {
      prod( x, y ) = T( 0 );
      for ( long k = 0; k < dimY(); k++ )
        prod( x, y ) += (*this)( x, k ) * other( k, y );
    }
```
Volume:
```
    {
      prod->at( x, y ) = T( 0 );
      for( long k = 0; k < size2[1]; k++ )
        prod->at( x, y ) += v1.at( x, k ) * v2.at( k, y );
    }
```
the iteration on k should stop at `size1[1]`, not `size2[1]`.
I'm fixing that and re-testing...
By bad...

**Comment by nsouedet** [comment]
You found it ? You are too strong ! Thank you very much.

**Comment by denisri** [comment]
You spoke about `DecomposedMotion`, that was exactly the good clue, I was far from finding that without it...

**Comment by denisri** [comment]
It doesn't solve the problem (changes nothing actually)... :(
However there was really a bug here, but it's not the only one...

**Comment by nsouedet** [comment]
I also have the same result :) 
(-175.255, 176.498, 0)

**Comment by nsouedet** [comment]
To me, the most probable guilty remains 7fb54f34359bedd7a7ba12d8be183283227d61cd (2021/04/28) because its changes are exactly modifying what is buggy ... no ?

**Comment by denisri** [comment]
Yes that's the changeset I was suspecting, and it was the one making use of matrix_product.

**Comment by denisri** [comment]
I confirm the faulty changeset is 7fb54f34359bedd7a7ba12d8be183283227d61cd. In the previous one, 05290b824cbd735f1178bcf1fb05378b940ae301, things were working.

**Comment by denisri** [comment]
In fact I must say that I don't understand at all the DecomposedAffineTransformation3d at all:
it inherits AffineTransformation3d, which holds a classical 4x4 matrix, but adds some additional information (shearing, scaling, rotation). However it doesn't overload any transform() method, and the methods which set/change the shearing/scaling/rotation data do not update the underlying AffineTransformation3d data. So how does it work at all ?

**Comment by denisri** [comment]
OK you were right at the first place, the problem is in the use of `deepcopy()` in `least_square_estimation.cc` (l. 250).
By removing the `deepcopy()`, I get the right result.

**Comment by nsouedet** [comment]
Many thanks Denis, 
Do you have any idea why was it a problem to deepcopy the rotation() ,matrix ?
Is there a parent volume shared between matrices ?

**Comment by denisri** [comment]
Yes, I was actually about to comment (and that's why I left the ticket open).
* First, do you confirm the problem is fixed for you after c65e1d5ee38ebac6c9e1e6bee2495afb944fa5bd ?
* in `least_square_estimation.cc`, l 250, in 5.0 we read:
   ```
     _motion->rot() = _motion->rotation().clone();
   ```
  which, for me, meant that the `rot()` data in `_motion` was copied from its `rotation()` data. However `rotation()` is now a 3x3 view into a 4x4 matrix, and it seems that in this case the values are not actually copied. This is why `clone()` was (I think) useless and wrong, but harmless in this specific situation. Thus I used Volume `deepcopy()` because I was mistaken by the `clone()`, and ended up with duplicated data, which did not work here.
* now I removed `deepcopy()`, the data is shared between `rot()` and `rotation()`, and it seems to work. This may be an answer to my question above, "how does `DecomposedAffineTransformation3d` work ?": it works when the affine matrix and the `rot()` matrix are the same shared data (am I right ?), then modifications to `rot()` also affect the affine part, and `transform()` works (I'm not sure it works completely however because scaling and shearing parts are not taken into account). But to me this shows how much `DecomposedAffineTransformation3d` is ill and mostly non-functional:
  * by default (on construction) rot() and rotation() are two distinct matrices. Thus they have to be forced the same from the exterior before it can work, which is really appalling...
  * why are there tho methods, `rot()` and `rotation()` which apparently do the same, are _not_ the same, but _must_ be the same ?
  * Are the shearing and scaling parts taken into account anywhere ?

**Comment by denisri** [comment]
While I check it, it seems that `AimsData::clone()` should also copy the underlying `refVolume()`, so I don't understand how it could end up with a shared matrix. Maybe there are more than 2 volume layers, which demonstrates a breach in clone()...

**Comment by denisri** [comment]
It's OK for this ticket: it's solved :)
But is there anyone having knowledge about `DecomposedAffineTransformation3d` ? I feel this class is broken and should be mostly rewritten, but I don't even know what it does and how it works (or should work)...
