### ISSUE TITLE
Aims data_type differs from datatype using nibabel

### ISSUE THREAD

**Issue by Hboni** [brainvisa/aims-free#59]
Trying to replace code using aims to not use it anymore, in the CatiDB server (where aims is not intended to be installed), we encounter a strange behavior.

We want to check the data_type of images, using aims we used to check `data_type` in the image header loaded using aims.
To replace it we wanted to use nibabel for the same check, but in the header of nibabel image loaded, `data_type` and `datatype` is the same values between S16 and FLOAT images. So we looked at data (`nib.load([...]).get_data()`) and check `.dtype.type` to really look at the type of values in the image.

To summarize this is a table with values obtains with different images. We can see the difference between image_1 and image_2 which does not have same data type between Aims and nibabel. The main difference between image_1 and image_2 is that image_1 is the output of dcm2nii, and the image_2 is explicitly converted to FLOAT using AimsFileConvert.

|               | Aims data_type | Aims disk_data_type | Aims scale_offset | nibabel dtype.type |
| :---------- | :----------: |  :----------: | :----------: | :----------: | 
| image_1 | S16 | FLOAT | 0 | np.int16 |
| image_2 | S16 | FLOAT | 824 | np.float64 |
| image_3 | S16 | S16 |  | np.int16 |

So we wanted to know why this difference appears and if we must believe the results from nibabel dtype.type or not?

**Comment by denisri** [comment]
Aims and nibabel follow different (internal) conventions to load images. Data types may differ, and voxels orientation also. I don't know how nibabel interprets things and have always avoided using it, precisely not to run into this kind of divergences... I can tell only for aims side.
I'm surprised that in your images the "`disk_data_type`" is float and the "`data_type`" is S16. Isn't it the contrary ? I assume you have inverted columns names, if I'm wrong, tell me.
The usual usecase is that data are stored as `S16` on disk but may have scale factors/offsets which get loaded data to float type. The rule we apply for that is: if the `scale_factor` is 0, then it is not applied (of course because it would erase all data) and we stay in int16 type: then both `data_type` and `disk_data_type` are int16 (I guess in your `image_3` is in this situation). If the `scale_factor` is not 0 (and even if it is 1 and `scale_offset` is 0) then we switch to float type (it's a way to indicate that we *want* float type even when float values are not used in this image). Maybe nibabel doesn't follow the same rule and loads as int16 data with a `scale_factor` 1 and `scale_offset` 0 (maybe your `image_1` ?).

**Comment by Hboni** [comment]
Oh yeah, you're right, I copy my table but inverted `data_type` and `disk_data_type`!
Ok, @sapetnioc talked about `scale_factor` as an important parameter for that, but I put `scale_offset` in my table :sweat_smile:. For image_1 and image_2 this `scale_factor` is 1, so It explained why in both cases Aims `data_type` is FLOAT!? I will dig more in nibabel documentation, as this scale factor is not in the header of images load with nibabel.

**Comment by sapetnioc** [comment]
What is the status of this issue ?

**Comment by denisri** [comment]
It's definitely not an issue on AIMS side, since the behaviour we have implemented is the only one which allows to specify that we want a float type image even if only int values are used.
