### ISSUE TITLE
Deprecate AimsData in a visible way

### ISSUE THREAD

**Issue by ylep** [brainvisa/aims-free#61]
- Change the header
- Add the __deprecated__ GCC attribute

**Comment by denisri** [comment]
A compiler warning has been when it's used unless the macro 
AIMSDATA_CLASS_NO_DEPREC_WARNING is defined. (#61)
The macro has been thus defined in most of our projects for now since 
the classes are still widely used. Thus it is not really completely obsolete, and not really completely warned yet, but we can remove the macro one piece of code after another when we are ready...

**Comment by Hboni** [comment]
I was trying to compile a casa-distro from scratch, and I get an error during build step: 
```
[ 95%] Built target AimsAttributedViewer
[ 95%] Generating sipaimsalgosippart0.cpp, sipaimsalgosippart1.cpp, sipaimsalgosippart2.cpp, sipaimsalgosippart3.cpp, sipaimsalgosippart4.cpp, sipaimsalgosippart5.cpp, sipaimsalgosippart6.cpp, sipaimsalgosippart7.cpp
Scanning dependencies of target anatomist-bin
[ 95%] Building CXX object build_files/anatomist-free/src/anatomist/CMakeFiles/anatomist-bin.dir/anatomist.cc.o
sip: Unable to find file "meshresampler_AimsData_U32.sip"
Error: sip exited with signal 1
build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/build.make:1016: recipe for target 'build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipaimsalgosippart0.cpp' failed
make[2]: *** [build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipaimsalgosippart0.cpp] Error 1
CMakeFiles/Makefile2:47785: recipe for target 'build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/all' failed
make[1]: *** [build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 95%] Linking CXX executable ../../../../bin/anatomist
[ 95%] Built target anatomist-bin
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/casa/host/build/bin/bv_maker", line 1104, in process
    **meth_kwargs)
  File "/casa/host/build/bin/bv_maker", line 4022, in build
    timeout=timeout)
  File "/casa/host/build/bin/bv_maker", line 428, in system
    six.reraise(*error)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/casa/host/build/bin/bv_maker", line 417, in system
    raise OSError()
OSError: Command failed: 'make' '-j2'
From directory: /casa/host/build

bv_maker summary:
FAILED      step build: /casa/host/build, started: 2021/08/20 11:05, stopped: 2021/08/20 11:09
```
As I saw that some changes were made in the lasts few days, I tried to checkout aims-free project to a previous commit (099d68523d367e82db766f82edd8526e07752981), and it builds well this time. I see several commits per day to fix this issue, do it could be better to make those changes in a specific branch, to not impact dev installations that are based on master branch?

**Comment by denisri** [comment]
`"meshresampler_AimsData_U32.sip"` has actually disapeared, and should be replaced with `"meshresampler_rc_ptr_Volume_U32.sip"`. This "templated" file is generated through `pyaimsalgo/src/sip/generatedtypes.py`, which has actually been modified to generate the mesh resampler for `Volume` instead of `AimsData` (https://github.com/brainvisa/aims-free/commit/9d8cee575884aae2caa639a064dea9270d5806c1#diff-5abe167b17b01e2910ddc05b056b43a5f65981c18697515f7482574377f995f0). And I have just checked that the master branch successfully builds for me (and also for the test server https://brainvisa.info/builds/job/brainvisa-master-5.0/lastSuccessfulBuild/) so I'm wondering if you have actually pulled all the updates...?

> As I saw that some changes were made in the lasts few days, I tried to checkout aims-free project to a previous commit (099d685), and it builds well this time. I see several commits per day to fix this issue, do it could be better to make those changes in a specific branch, to not impact dev installations that are based on master branch?

I partly agree and admit that I'm sometimes trying to do things too quickly because of lack of time to perform deep modifications, and I apologize for that. However working on a feature branch (and I'm actually doing it currently) doesn't allow to test things because the test server (https://brainvisa.info/builds) doesn't test feature branches, so when things seem to work on my side I need to push things on master from time to time.... We have had many hesitations on the handling of branches (we formerly used an "integration" branch, and dropped it with the release 5.0), now production and stable code is on 5.0, master may undergo deep modifs.

**Comment by Hboni** [comment]
I created from scratch everythong this morning, so I may have the most recent sources I guess. I created a cati_platform distro, maybe somemthing is missing in it?

If you tried on your side, as I though, and nothing wrong shows with you it's ok, I am not aware of ALL the test/code infrastructure that you deploy, I was just wondering. Thanks to add precisions about it. So it may be an issue specific to me :+1:

**Comment by Hboni** [comment]
Switching to main HEAD of aims-free does not generate an error in the build step anymore. :+1: 
Thanks!

**Comment by denisri** [comment]
I have merged my work branch which completely wipe out `AimsData` classes in python: the SIP bindings now map them to `Volume` or `rc_ptr_Volume`. I changed all python code which were still using `AimsData` (using `grep`) but I can't guarantee that all functions expecting an `AimsData` instance have been modified (there might remain some functions using `AimsData` methods on objects passed to them, like `volume.dimX()` for instance). Tests and experience will tell...

**Comment by Hboni** [comment]
Trying to use `anasimpleviewer.py` after updating my casa-distro, (to check GUI with anatomist) with an image as input, gets me this error:
```
Traceback (most recent call last):
  File "/casa/host/build/bin/anasimpleviewer.py", line 100, in <module>
    anasimple.loadObject(i)
  File "/casa/host/build/python/anatomist/simpleviewer/anasimpleviewer.py", line 375, in loadObject
    self.registerObject(obj)
  File "/casa/host/build/python/anatomist/simpleviewer/anasimpleviewer.py", line 411, in registerObject
    ana.cpp.AObjectConverter.aims(obj))
  File "/casa/host/build/python/anatomist/cpp/__init__.py", line 225, in aimsFromAnatomist
    aim = AObjectConverter.aimsData_U8(ao, options)
AttributeError: type object 'AObjectConverter' has no attribute 'aimsData_U8'
Exiting Anatomist --- Goodbye.
```

**Comment by denisri** [comment]
Right, I'm fixing that ASAP.

**Comment by denisri** [comment]
It's fixed.

**Comment by Hboni** [comment]
Thanks, but now I get another error, with another format. I thought it would be my image format, but we must not have this type of error?
```Traceback (most recent call last):
  File "/casa/host/build/bin/anasimpleviewer.py", line 100, in <module>
    anasimple.loadObject(i)
  File "/casa/host/build/python/anatomist/simpleviewer/anasimpleviewer.py", line 375, in loadObject
    self.registerObject(obj)
  File "/casa/host/build/python/anatomist/simpleviewer/anasimpleviewer.py", line 411, in registerObject
    ana.cpp.AObjectConverter.aims(obj))
  File "/casa/host/build/python/anatomist/cpp/__init__.py", line 237, in aimsFromAnatomist
    aim = AObjectConverter.volume_U32(ao, options)
AttributeError: type object 'AObjectConverter' has no attribute 'volume_U32'
Exiting Anatomist --- Goodbye.
```

I double check, I am on master branch for all the projects (aims-*, anatomis-*, ....) and all are up-to-date.

**Comment by denisri** [comment]
Right too. This function exists in C++ code but has been forgotten in python bindings. It's fixed.

**Comment by Hboni** [comment]
Thanks for you quick fixes, anasimpleviewer work well now for me! :tada:

**Comment by denisri** [comment]
An important step has been reached: `AimsData` classes are not used any longer in the main aims API (aimsdata and aimsalgo) except for classes which define them and their IO. All code can be written using only `Volume` now.
pyaims bindings don't use them at all any longer (internal MappedTypes have been removed)
Deprecation warnings have been activated for aims (and anatomist)

Commandlines still use the obsolete classes, however. Cleaning them is a huge work.
