### ISSUE TITLE
2D distance map creation problem

### ISSUE THREAD

**Issue by tdelzescaux** [brainvisa/aims-free#63]
When creating a distance map from a 2D binary mask, only the FORWARD step is applied.

**Comment by denisri** [comment]
Can you precise please ? I don't know what you are talking about (which kind of distance map, or command, or...?)

**Comment by tdelzescaux** [comment]
Here is an example with a disk: 
[data.zip](https://github.com/brainvisa/aims-free/files/6830697/data.zip)
AimsChamferDistanceMap -i disk.ima -o disk_dist.ima 
Also tried to modify z mask size with the same result. Data attached. 
[data.zip](https://github.com/brainvisa/aims-free/files/6830700/data.zip)

**Comment by denisri** [comment]
I see... That's strange, the behavior is different in 3D, but still strange (we get negative distances). Has it always been so ? (I don't know as we use Fastmarching distance maps most of the time, nowadays)

**Comment by denisri** [comment]
The negative values are normal in "signed" distance mode (the default). So the problem is really that it doesn't work on 2D images. Trying older releases it seems that it was working in brainvisa 4.5, and broken in 4.6. However the code for the chamfer distance maps has not been modified for 12 years (way older than 4.5), so it's probably a subtle side effect of volume structures modification, border handling or something like that (or the random of uninitialized borders).
