### ISSUE TITLE
AimsGraphMesh does not create a .minf file for its output

### ISSUE THREAD

**Issue by ylep** [brainvisa/aims-free#76]
**Describe the bug**
`AimsGraphMesh` does not create a `.minf` file for its output, so many attributes are lost (including the referentials and transformations).

**To Reproduce**
1. Start from a ROI Graph (`RoiArg` syntax) such as the ROI graphs created by the ROI Toolbox in Anatomist.
2. Run `AimsGraphMesh` on that graph: `AimsGraphMesh -i roi.arg -o meshed.arg`
3. There is no `meshed.arg.minf` file

**Expected behavior**
The information in the input `.minf` should be carried along into the output.

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA : 5.0.4

**Comment by denisri** [comment]
The command is using old low-level IO in order to tune writing options. But these low-level IO do not deal with the .minf. I'm fixing it by adding options passed through the high-level IO layer API, but it involves an API change in the intermediate-level graph IO API. So I will fix it in the master branch only I think.
